### ISSUE TITLE
I2C communications are unstable without this delay

### ISSUE THREAD

**Issue by tganley** [AlbertaSat/ex2_obc_software#86]
This delay significantly slows down communications over i2c and should not be necessary, but without it the bus often gets stuck in a latched state which software resets do not solve and hardware resets solve inconsistently. Suggest rework of the interrupt service routine.

https://github.com/AlbertaSat/ex2_obc_software/blob/6c0bc80ccbab907d26e1e0ccb6df94b4e8de7aea/source/i2c_io.c#L86

**Comment by Taylorr82** [comment]
This got fixed at some point, there's no longer a delay in i2c_io.c
