### ISSUE TITLE
U_ANS_SUCCESS is not defined anywhere

### ISSUE THREAD

**Issue by Taylorr82** [AlbertaSat/ex2_obc_software#96]
https://github.com/AlbertaSat/ex2_obc_software/blob/5da9c9073df77d7fc13ee826190a646e7dbc353b/ex2_system/source/diagnostic/diagnostic.c#L75

**Comment by tganley** [comment]
Hm yeah the change is currently in the cleanup_rebase branch which I intend to merge very soon

**Comment by Taylorr82** [comment]
Has this been fixed?

**Comment by tganley** [comment]
#99 Fixed this from obc_software perspective
